global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'RECIPIENT_EMAIL_HERE@gmail.com'
    from: 'SENDER_EMAIL_HERE@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'SENDER_EMAIL_HERE@gmail.com'
    auth_identity: 'SENDER_EMAIL_HERE@gmail.com'
    auth_password: 'SEARCH HOW TO GENERATE GOOGLE ACCOUNT APP PASSWORDS'
