scrape_configs:

  - job_name: 'example-ap'
    scrape_interval: 5s
    static_configs:
      - targets: ['example-app:9000']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']


